#!/bin/bash

workpath="/foo/"
screen_name="bar"
cmd="command"
logfile="bar.log"

echo -e "screen start: ${screen_name}\n"

screen -dmS "${screen_name}"

while true; do
    if screen -ls | grep -q "${screen_name}"; then
        break;
    fi
done

screen -x -S "${screen_name}" -p 0 -X stuff "cd \"${workpath}\" && $cmd |& tee -a \"${logfile}\""
screen -x -S "${screen_name}" -p 0 -X stuff $'\n'
