#!/bin/bash

workpath="/foo/"
screen_name="bar"
cmd="command"
logfile="bar.log"

echo -e "screen start: ${screen_name}\n"

screen -dmS "${screen_name}"

while true; do
    if screen -ls | grep -q "${screen_name}"; then
        break;
    fi
done

if [ -n "${logfile}" ]; then
    log_command=" 2>&1 | tee -a \"${logfile}\""
else 
    log_command=""
fi


screen -x -S "${screen_name}" -p 0 -X stuff "cd \"${workpath}\" && ${cmd}${log_command}"
screen -x -S "${screen_name}" -p 0 -X stuff $'\n'
